name: production-calculator
services:
  backend:
    build: ./backend/ProductionCalculator.API
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV_NAME:-dev}
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    depends_on:
      - postgres
    secrets:
      - server_password

  postgres:
    image: postgres:18
    container_name: postgres_${ENV_NAME:-dev}
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: production_calculator
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./database/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "${DB_PORT:-5151}:5432"
    secrets:
      - postgres_password

  flyway:
    image: flyway/flyway:10
    container_name: flyway_${ENV_NAME:-dev}
    depends_on:
      - postgres
    volumes:
      - ./database/migrations:/flyway/sql
      - ./scripts/flyway-entrypoint.sh:/flyway-entrypoint.sh
    entrypoint: ["/bin/sh", "/flyway-entrypoint.sh"]
    command: -url=jdbc:postgresql://postgres:5432/production_calculator -user=flyway migrate
    restart: "no"
    secrets:
      - flyway_password

volumes:
  db_data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  flyway_password:
    file: ./secrets/flyway_password.txt
  server_password:
    file: ./secrets/server_password.txt
