name: production-calculator
services:
  backend:
    image: production-calculator_backend
    container_name: backend_${ENV_NAME:-Development}
    build: ./backend
    restart: always
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV_NAME:-Development}
    volumes:
      - ./scripts/backend-entrypoint.sh:/backend-entrypoint.sh
    entrypoint: ["/bin/sh", "/backend-entrypoint.sh"]
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      flyway:
        condition: service_completed_successfully
    secrets:
      - server_password

  postgres:
    image: postgres:18
    container_name: postgres_${ENV_NAME:-Development}
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: production_calculator
    volumes:
      - db_data:/var/lib/postgresql
      - ./database/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./database/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "${DB_PORT:-5150}:5432"
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  flyway:
    image: flyway/flyway:10
    container_name: flyway_${ENV_NAME:-Development}
    depends_on:
      - postgres
    volumes:
      - ./database/migrations:/flyway/sql
      - ./scripts/flyway-entrypoint.sh:/flyway-entrypoint.sh
    entrypoint: ["/bin/sh", "/flyway-entrypoint.sh"]
    command: -url=jdbc:postgresql://postgres:5432/production_calculator -user=flyway migrate
    restart: "no"
    secrets:
      - flyway_password

volumes:
  db_data:

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  flyway_password:
    file: ./secrets/flyway_password.txt
  server_password:
    file: ./secrets/server_password.txt
